export const FULL_CIRCLE_ANGLE = Math.PI * 2
export const ANGULAR_SPEED = 1.4
export const MAX_FRAME_DELTA_TIME = 0.05
export const MAX_PLAYER_COLLISION_STEP_TIME = 1 / 240
export const PLAYER_RADIUS = 7
export const PLAYER_WALL_CLEARANCE = 2
export const MOTION_TILT_DEAD_ZONE_DEGREES = 4
export const MOTION_TILT_FULL_SPEED_DEGREES = 17.5
export const DEBUG_MOTION_RADIAL_SENSITIVITY = 2

export const HEART_RATE_BASELINE_BPM = 70
export const HEART_RATE_RADIAL_SPEED = 60
export const HEART_RATE_SMOOTHING_FACTOR = 0.15
export const MIN_VALID_BPM = 35
export const MAX_VALID_BPM = 220
export const DEBUG_HEART_RATE_STEP_BPM = 1
export const CALIBRATION_DURATION_MS = 20_000
export const HEART_RATE_NEUTRAL_OFFSET_BPM = 10
export const HEART_RATE_INWARD_FULL_OFFSET_BPM = -5
export const HEART_RATE_OUTWARD_FULL_OFFSET_BPM = 15
export const RADIAL_FACTOR_MIN = -1
export const RADIAL_FACTOR_MAX = 1
export const STALE_BPM_TIMEOUT_MS = 3_000
export const MAX_SESSION_DURATION_MS = 10 * 60 * 1_000
export const PULSE_GRAPH_HISTORY_LENGTH = 200

export const MAZE_RING_COUNT = 5
export const MAZE_SECTOR_COUNT = 12
export const MAZE_CENTER_RADIUS = 48
export const MAZE_RING_WIDTH = 40
export const MAZE_OUTER_RADIUS = MAZE_CENTER_RADIUS + MAZE_RING_COUNT * MAZE_RING_WIDTH
export const MAZE_RENDER_PADDING = 24
export const MAZE_WALL_WIDTH = 2
export const SECTOR_ANGLE = FULL_CIRCLE_ANGLE / MAZE_SECTOR_COUNT
export const MIN_SOLUTION_PATH_CELLS = 30
export const MIN_SOLUTION_BRANCHES = 2
export const MAX_MAZE_GENERATION_ATTEMPTS = 100

export const PLAYER_START_RADIUS = 0
export const PLAYER_START_ANGLE = SECTOR_ANGLE / 2

export const GAME_BACKGROUND_COLOR = '#fbfbf9'
export const MAZE_WALL_COLOR = '#111111'
export const PLAYER_COLOR = '#9f1d2a'
